---

- name: NODEJS DEBIAN | Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - python-software-properties

- name: NODEJS DEBIAN | Download configuration script
  get_url:
    url: https://deb.nodesource.com/setup_{{ nodejs_version }}
    dest: /tmp/nodejs_{{ nodejs_version }}.sh
    owner: root
    group: root
    mode: 0744
