---

- name: NODEJS DEBIAN | Install prerequisites
  apt:
    name:
    - curl
    - python3-software-properties
    state: present

- name: NODEJS DEBIAN | Download configuration script
  get_url:
    url: https://deb.nodesource.com/setup_{{ nodejs_version }}
    dest: /tmp/nodejs_{{ nodejs_version }}.sh
    owner: root
    group: root
    mode: 0744
