---

- name: NODEJS REDHAT | Install prerequisites
  package:
    name:
      - gcc-c++
      - make
    state: present
    
- name: NODEJS DEBIAN | Download configuration script
  get_url:
    url: https://rpm.nodesource.com/setup_{{ nodejs_version }}
    dest: /tmp/nodejs_{{ nodejs_version }}.sh
    owner: root
    group: root
    mode: 0744
